name: ringo_media_management
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  flutter_hooks: ^0.20.5
  auto_route: ^8.1.4
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  kt_dart: ^1.1.0
  rxdart: ^0.28.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  connectivity_plus: ^5.0.2
  uuid: ^4.4.2
  firebase_auth: 5.1.2
  firebase_core: 3.2.0
  cloud_firestore: ^5.1.0
  shared_preferences: ^2.2.3
  in_date_utils: ^1.2.1
  new_version_plus: ^0.0.11
  cloud_functions: ^5.0.3
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  internet_connection_checker_plus: ^2.2.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/menu/
    - assets/svgs/auth/
    - assets/svgs/home_team_workspace/
    - assets/launcher_icon/dev/
    - assets/launcher_icon/prod/
    - assets/launcher_icon/dev/
    - config/